global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']

  - job_name: 'processor'
    metrics_path: /metrics
    static_configs:
      - targets: ['processor:9090']

  - job_name: 'risk-engine'
    metrics_path: /metrics
    static_configs:
      - targets: ['risk-engine:9090']
